### ISSUE TITLE
When running the tests console shows UNHANDLED_ERROR in the logs

### ISSUE THREAD

**Issue by jpoo90** [thescientist13/github-dashboard#149]
```
UNHANDLED ERROR { Error: Request failed with status code 404
        at createErrorResponse (/Users/jp/Documents/github-dashboard/node_modules/axios-mock-adapter/src/utils.js:87:15)
        at Object.settle (/Users/jp/Documents/github-dashboard/node_modules/axios-mock-adapter/src/utils.js:67:16)
        at handleRequest (/Users/jp/Documents/github-dashboard/node_modules/axios-mock-adapter/src/handle_request.js:53:11)
        at /Users/jp/Documents/github-dashboard/node_modules/axios-mock-adapter/src/index.js:16:9
        at MockAdapter.<anonymous> (/Users/jp/Documents/github-dashboard/node_modules/axios-mock-adapter/src/index.js:15:14)
        at dispatchRequest (/Users/jp/Documents/github-dashboard/node_modules/axios/lib/core/dispatchRequest.js:52:10)
        at process._tickCallback (internal/process/next_tick.js:103:7)
```

I was able to narrow down the issue to `bootstrap.spec.jsx`. When this suit runs, multiple errors like the one above appear. I'll give it a try to see if I'm able to solve it.

**Comment by thescientist13** [comment]
@jpoo90 
What versions of Node / Yarn do you have?
```
$ node -v
v6.9.1
obuckleyMBP:github-dashboard obuckley$ yarn -v
yarn install v0.21.3
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.59s.
``

I did a `yarn cache clean` and `yarn install` and got the warning about `ReactTestUtils`

```bash
 Warning: ReactTestUtils has been moved to react-dom/test-utils. Update references to remove this warning.
```

but not that _UNHANDLED ERROR_ specifically though : /

I've noticed in other projects using latest version of Yarn (0.23.x) has caused some issues, so I've been sticking to just 0.21.3 for now

**Comment by jpoo90** [comment]
@thescientist13 I have 

```
$ node -v
v6.9.5
```

```
$ yarn -v
v0.21.3
```

I just re-installed the project from scratch in my fork, and got the same errors 🤔

**Comment by thescientist13** [comment]
@jpoo90 
For the other issues reported / seen, I have made
- #150 
- #151

**Comment by thescientist13** [comment]
Reviewed with @jpoo90 and the issue is with the hard coded username in the spec
https://github.com/thescientist13/github-dashboard/blob/master/src/components/bootstrap/bootstrap.spec.jsx#L32
